services:
  db:
    image: postgres:16
    container_name: f1_group_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: f1_group_app
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./storage:/app/storage

volumes:
  postgres_data: